import type { Vocab } from '@/types'

// Japonca temel kelime hazinesi (N5 ağırlıklı).
// Romaji çalışma anında wanakana ile okunuştan üretilir; burada yazılmaz.
//
// Satır biçimi: [terim, okunuş, türkçe, tür, tema, örnek?, örnek okunuş?, örnek türkçe?]

type Row = [string, string, string, string, string, string?, string?, string?]

const POS_TR: Record<string, string> = {
  n: 'isim',
  v1: 'ichidan fiil (ru-fiil)',
  v5: 'godan fiil (u-fiil)',
  virr: 'düzensiz fiil',
  adji: 'i-sıfat',
  adjna: 'na-sıfat',
  adv: 'zarf',
  part: 'edat/ek',
  pron: 'zamir',
  num: 'sayı',
  exp: 'kalıp',
  conj: 'bağlaç',
  pre: 'ön-belirteç',
  cnt: 'sayaç',
}

const ROWS: Row[] = [
  // ————— Selamlaşma ve günlük kalıplar —————
  ['こんにちは', 'こんにちは', 'merhaba (gündüz)', 'exp', 'selamlasma', 'こんにちは、田中さん。', 'こんにちは、たなかさん。', 'Merhaba Tanaka bey.'],
  ['おはようございます', 'おはようございます', 'günaydın (kibar)', 'exp', 'selamlasma'],
  ['こんばんは', 'こんばんは', 'iyi akşamlar', 'exp', 'selamlasma'],
  ['さようなら', 'さようなら', 'hoşça kal', 'exp', 'selamlasma'],
  ['ありがとうございます', 'ありがとうございます', 'teşekkür ederim', 'exp', 'selamlasma'],
  ['すみません', 'すみません', 'affedersiniz / özür dilerim', 'exp', 'selamlasma', 'すみません、駅はどこですか。', 'すみません、えきはどこですか。', 'Affedersiniz, istasyon nerede?'],
  ['はじめまして', 'はじめまして', 'memnun oldum (ilk tanışma)', 'exp', 'selamlasma'],
  ['おやすみなさい', 'おやすみなさい', 'iyi geceler', 'exp', 'selamlasma'],
  ['いただきます', 'いただきます', 'afiyet olsun (yemekten önce)', 'exp', 'selamlasma'],
  ['お願いします', 'おねがいします', 'lütfen / rica ederim', 'exp', 'selamlasma', 'コーヒーをお願いします。', 'コーヒーをおねがいします。', 'Bir kahve lütfen.'],

  // ————— Zamirler ve soru sözcükleri —————
  ['私', 'わたし', 'ben', 'pron', 'zamir', '私は学生です。', 'わたしはがくせいです。', 'Ben öğrenciyim.'],
  ['あなた', 'あなた', 'sen/siz', 'pron', 'zamir'],
  ['彼', 'かれ', 'o (erkek)', 'pron', 'zamir'],
  ['彼女', 'かのじょ', 'o (kadın) / kız arkadaş', 'pron', 'zamir'],
  ['これ', 'これ', 'bu (konuşana yakın)', 'pron', 'zamir', 'これは本です。', 'これはほんです。', 'Bu bir kitap.'],
  ['それ', 'それ', 'şu (dinleyene yakın)', 'pron', 'zamir'],
  ['あれ', 'あれ', 'o (ikisinden de uzak)', 'pron', 'zamir'],
  ['この', 'この', 'bu ... (isimden önce)', 'pre', 'zamir', 'この人は先生です。', 'このひとはせんせいです。', 'Bu kişi öğretmen.'],
  ['その', 'その', 'şu ...', 'pre', 'zamir'],
  ['あの', 'あの', 'o ...', 'pre', 'zamir'],
  ['ここ', 'ここ', 'burası', 'pron', 'zamir'],
  ['そこ', 'そこ', 'şurası', 'pron', 'zamir'],
  ['あそこ', 'あそこ', 'orası', 'pron', 'zamir'],
  ['誰', 'だれ', 'kim', 'pron', 'soru', 'あの人は誰ですか。', 'あのひとはだれですか。', 'O kişi kim?'],
  ['何', 'なに', 'ne', 'pron', 'soru', 'これは何ですか。', 'これはなんですか。', 'Bu ne?'],
  ['どこ', 'どこ', 'nerede', 'pron', 'soru'],
  ['いつ', 'いつ', 'ne zaman', 'pron', 'soru'],
  ['どう', 'どう', 'nasıl', 'adv', 'soru'],
  ['どうして', 'どうして', 'neden', 'adv', 'soru'],
  ['どれ', 'どれ', 'hangisi', 'pron', 'soru'],
  ['いくら', 'いくら', 'ne kadar (fiyat)', 'pron', 'soru', 'これはいくらですか。', 'これはいくらですか。', 'Bu ne kadar?'],
  ['いくつ', 'いくつ', 'kaç tane', 'pron', 'soru'],

  // ————— İnsanlar —————
  ['人', 'ひと', 'insan, kişi', 'n', 'insan'],
  ['友だち', 'ともだち', 'arkadaş', 'n', 'insan', '友だちと映画を見ます。', 'ともだちとえいがをみます。', 'Arkadaşımla film izliyorum.'],
  ['先生', 'せんせい', 'öğretmen', 'n', 'insan'],
  ['学生', 'がくせい', 'öğrenci', 'n', 'insan'],
  ['子ども', 'こども', 'çocuk', 'n', 'insan'],
  ['家族', 'かぞく', 'aile', 'n', 'insan'],
  ['父', 'ちち', 'babam', 'n', 'insan'],
  ['母', 'はは', 'annem', 'n', 'insan'],
  ['お父さん', 'おとうさん', 'baba (başkasının)', 'n', 'insan'],
  ['お母さん', 'おかあさん', 'anne (başkasının)', 'n', 'insan'],
  ['兄', 'あに', 'ağabeyim', 'n', 'insan'],
  ['姉', 'あね', 'ablam', 'n', 'insan'],
  ['弟', 'おとうと', 'küçük erkek kardeşim', 'n', 'insan'],
  ['妹', 'いもうと', 'küçük kız kardeşim', 'n', 'insan'],
  ['会社員', 'かいしゃいん', 'şirket çalışanı', 'n', 'insan'],
  ['医者', 'いしゃ', 'doktor', 'n', 'insan'],

  // ————— Yerler —————
  ['家', 'いえ', 'ev', 'n', 'yer', '家に帰ります。', 'いえにかえります。', 'Eve dönüyorum.'],
  ['学校', 'がっこう', 'okul', 'n', 'yer'],
  ['大学', 'だいがく', 'üniversite', 'n', 'yer'],
  ['会社', 'かいしゃ', 'şirket', 'n', 'yer'],
  ['駅', 'えき', 'istasyon', 'n', 'yer'],
  ['店', 'みせ', 'dükkân', 'n', 'yer'],
  ['銀行', 'ぎんこう', 'banka', 'n', 'yer'],
  ['病院', 'びょういん', 'hastane', 'n', 'yer'],
  ['図書館', 'としょかん', 'kütüphane', 'n', 'yer'],
  ['部屋', 'へや', 'oda', 'n', 'yer'],
  ['トイレ', 'といれ', 'tuvalet', 'n', 'yer'],
  ['公園', 'こうえん', 'park', 'n', 'yer'],
  ['国', 'くに', 'ülke', 'n', 'yer'],
  ['日本', 'にほん', 'Japonya', 'n', 'yer'],
  ['トルコ', 'とるこ', 'Türkiye', 'n', 'yer', '私はトルコから来ました。', 'わたしはとるこからきました。', 'Ben Türkiye\'den geldim.'],

  // ————— Nesneler —————
  ['本', 'ほん', 'kitap', 'n', 'nesne'],
  ['車', 'くるま', 'araba', 'n', 'nesne'],
  ['電話', 'でんわ', 'telefon', 'n', 'nesne'],
  ['時計', 'とけい', 'saat (nesne)', 'n', 'nesne'],
  ['かばん', 'かばん', 'çanta', 'n', 'nesne'],
  ['傘', 'かさ', 'şemsiye', 'n', 'nesne'],
  ['お金', 'おかね', 'para', 'n', 'nesne'],
  ['新聞', 'しんぶん', 'gazete', 'n', 'nesne'],
  ['写真', 'しゃしん', 'fotoğraf', 'n', 'nesne'],
  ['机', 'つくえ', 'masa (çalışma)', 'n', 'nesne'],
  ['椅子', 'いす', 'sandalye', 'n', 'nesne'],
  ['服', 'ふく', 'kıyafet', 'n', 'nesne'],
  ['靴', 'くつ', 'ayakkabı', 'n', 'nesne'],
  ['鍵', 'かぎ', 'anahtar', 'n', 'nesne'],
  ['手紙', 'てがみ', 'mektup', 'n', 'nesne'],

  // ————— Yiyecek içecek —————
  ['水', 'みず', 'su', 'n', 'yemek'],
  ['お茶', 'おちゃ', 'çay', 'n', 'yemek'],
  ['コーヒー', 'こーひー', 'kahve', 'n', 'yemek'],
  ['ご飯', 'ごはん', 'pilav / yemek', 'n', 'yemek'],
  ['パン', 'ぱん', 'ekmek', 'n', 'yemek'],
  ['肉', 'にく', 'et', 'n', 'yemek'],
  ['魚', 'さかな', 'balık', 'n', 'yemek'],
  ['野菜', 'やさい', 'sebze', 'n', 'yemek'],
  ['果物', 'くだもの', 'meyve', 'n', 'yemek'],
  ['卵', 'たまご', 'yumurta', 'n', 'yemek'],
  ['牛乳', 'ぎゅうにゅう', 'süt', 'n', 'yemek'],
  ['朝ご飯', 'あさごはん', 'kahvaltı', 'n', 'yemek'],
  ['昼ご飯', 'ひるごはん', 'öğle yemeği', 'n', 'yemek'],
  ['晩ご飯', 'ばんごはん', 'akşam yemeği', 'n', 'yemek'],

  // ————— Zaman —————
  ['今日', 'きょう', 'bugün', 'n', 'zaman'],
  ['明日', 'あした', 'yarın', 'n', 'zaman'],
  ['昨日', 'きのう', 'dün', 'n', 'zaman'],
  ['朝', 'あさ', 'sabah', 'n', 'zaman'],
  ['昼', 'ひる', 'öğle', 'n', 'zaman'],
  ['夜', 'よる', 'gece', 'n', 'zaman'],
  ['今', 'いま', 'şimdi', 'n', 'zaman'],
  ['毎日', 'まいにち', 'her gün', 'n', 'zaman', '毎日日本語を勉強します。', 'まいにちにほんごをべんきょうします。', 'Her gün Japonca çalışıyorum.'],
  ['時間', 'じかん', 'zaman, saat', 'n', 'zaman'],
  ['週末', 'しゅうまつ', 'hafta sonu', 'n', 'zaman'],
  ['去年', 'きょねん', 'geçen yıl', 'n', 'zaman'],
  ['来年', 'らいねん', 'gelecek yıl', 'n', 'zaman'],

  // ————— Fiiller —————
  ['食べる', 'たべる', 'yemek', 'v1', 'fiil', '寿司を食べます。', 'すしをたべます。', 'Suşi yiyorum.'],
  ['飲む', 'のむ', 'içmek', 'v5', 'fiil', '水を飲みます。', 'みずをのみます。', 'Su içiyorum.'],
  ['見る', 'みる', 'görmek, izlemek', 'v1', 'fiil'],
  ['聞く', 'きく', 'dinlemek, sormak', 'v5', 'fiil'],
  ['話す', 'はなす', 'konuşmak', 'v5', 'fiil', '日本語を話します。', 'にほんごをはなします。', 'Japonca konuşuyorum.'],
  ['読む', 'よむ', 'okumak', 'v5', 'fiil'],
  ['書く', 'かく', 'yazmak', 'v5', 'fiil'],
  ['行く', 'いく', 'gitmek', 'v5', 'fiil', '学校へ行きます。', 'がっこうへいきます。', 'Okula gidiyorum.'],
  ['来る', 'くる', 'gelmek', 'virr', 'fiil'],
  ['する', 'する', 'yapmak', 'virr', 'fiil'],
  ['帰る', 'かえる', 'eve dönmek', 'v5', 'fiil'],
  ['買う', 'かう', 'satın almak', 'v5', 'fiil'],
  ['会う', 'あう', 'buluşmak', 'v5', 'fiil'],
  ['起きる', 'おきる', 'kalkmak, uyanmak', 'v1', 'fiil'],
  ['寝る', 'ねる', 'uyumak', 'v1', 'fiil'],
  ['働く', 'はたらく', 'çalışmak (iş)', 'v5', 'fiil'],
  ['勉強する', 'べんきょうする', 'ders çalışmak', 'virr', 'fiil'],
  ['分かる', 'わかる', 'anlamak', 'v5', 'fiil', '意味が分かりません。', 'いみがわかりません。', 'Anlamını anlamıyorum.'],
  ['ある', 'ある', 'var olmak (cansız)', 'v5', 'fiil'],
  ['いる', 'いる', 'var olmak (canlı)', 'v1', 'fiil'],
  ['待つ', 'まつ', 'beklemek', 'v5', 'fiil'],
  ['作る', 'つくる', 'yapmak, üretmek', 'v5', 'fiil'],
  ['教える', 'おしえる', 'öğretmek', 'v1', 'fiil'],
  ['習う', 'ならう', 'öğrenmek (birinden)', 'v5', 'fiil'],
  ['使う', 'つかう', 'kullanmak', 'v5', 'fiil'],
  ['入る', 'はいる', 'girmek', 'v5', 'fiil'],
  ['出る', 'でる', 'çıkmak', 'v1', 'fiil'],
  ['歩く', 'あるく', 'yürümek', 'v5', 'fiil'],
  ['乗る', 'のる', 'binmek', 'v5', 'fiil'],
  ['休む', 'やすむ', 'dinlenmek', 'v5', 'fiil'],

  // ————— Sıfatlar —————
  ['大きい', 'おおきい', 'büyük', 'adji', 'sifat'],
  ['小さい', 'ちいさい', 'küçük', 'adji', 'sifat'],
  ['新しい', 'あたらしい', 'yeni', 'adji', 'sifat'],
  ['古い', 'ふるい', 'eski', 'adji', 'sifat'],
  ['高い', 'たかい', 'yüksek, pahalı', 'adji', 'sifat', 'この車は高いです。', 'このくるまはたかいです。', 'Bu araba pahalı.'],
  ['安い', 'やすい', 'ucuz', 'adji', 'sifat'],
  ['いい', 'いい', 'iyi', 'adji', 'sifat'],
  ['悪い', 'わるい', 'kötü', 'adji', 'sifat'],
  ['おいしい', 'おいしい', 'lezzetli', 'adji', 'sifat'],
  ['忙しい', 'いそがしい', 'meşgul', 'adji', 'sifat'],
  ['楽しい', 'たのしい', 'eğlenceli', 'adji', 'sifat'],
  ['難しい', 'むずかしい', 'zor', 'adji', 'sifat'],
  ['易しい', 'やさしい', 'kolay', 'adji', 'sifat'],
  ['暑い', 'あつい', 'sıcak (hava)', 'adji', 'sifat'],
  ['寒い', 'さむい', 'soğuk (hava)', 'adji', 'sifat'],
  ['面白い', 'おもしろい', 'ilginç, eğlenceli', 'adji', 'sifat'],
  ['元気', 'げんき', 'sağlıklı, enerjik', 'adjna', 'sifat', 'お元気ですか。', 'おげんきですか。', 'Nasılsınız?'],
  ['静か', 'しずか', 'sessiz', 'adjna', 'sifat'],
  ['にぎやか', 'にぎやか', 'canlı, hareketli', 'adjna', 'sifat'],
  ['きれい', 'きれい', 'güzel, temiz', 'adjna', 'sifat'],
  ['有名', 'ゆうめい', 'ünlü', 'adjna', 'sifat'],
  ['便利', 'べんり', 'kullanışlı', 'adjna', 'sifat'],
  ['好き', 'すき', 'sevilen, hoşlanılan', 'adjna', 'sifat', '寿司が好きです。', 'すしがすきです。', 'Suşi severim.'],
  ['嫌い', 'きらい', 'sevilmeyen', 'adjna', 'sifat'],
  ['上手', 'じょうず', 'usta, iyi (bir işte)', 'adjna', 'sifat'],
  ['下手', 'へた', 'beceriksiz', 'adjna', 'sifat'],

  // ————— Zarflar ve bağlaçlar —————
  ['とても', 'とても', 'çok', 'adv', 'zarf'],
  ['少し', 'すこし', 'biraz', 'adv', 'zarf'],
  ['たくさん', 'たくさん', 'bir sürü', 'adv', 'zarf'],
  ['よく', 'よく', 'sık sık, iyice', 'adv', 'zarf'],
  ['ときどき', 'ときどき', 'bazen', 'adv', 'zarf'],
  ['あまり', 'あまり', 'pek (olumsuzla)', 'adv', 'zarf', 'あまり分かりません。', 'あまりわかりません。', 'Pek anlamıyorum.'],
  ['全然', 'ぜんぜん', 'hiç (olumsuzla)', 'adv', 'zarf'],
  ['もう', 'もう', 'artık, çoktan', 'adv', 'zarf'],
  ['まだ', 'まだ', 'henüz, hâlâ', 'adv', 'zarf'],
  ['そして', 'そして', 've, sonra', 'conj', 'baglac'],
  ['でも', 'でも', 'ama', 'conj', 'baglac'],
  ['だから', 'だから', 'bu yüzden', 'conj', 'baglac'],
  ['それから', 'それから', 'ondan sonra', 'conj', 'baglac'],
  ['じゃあ', 'じゃあ', 'o zaman, öyleyse', 'conj', 'baglac'],

  // ————— Vücut ve sağlık (Genki 12 civarı) —————
  ['頭', 'あたま', 'baş, kafa', 'n', 'vucut', '頭が痛いです。', 'あたまがいたいです。', 'Başım ağrıyor.'],
  ['目', 'め', 'göz', 'n', 'vucut'],
  ['耳', 'みみ', 'kulak', 'n', 'vucut'],
  ['口', 'くち', 'ağız', 'n', 'vucut'],
  ['手', 'て', 'el', 'n', 'vucut'],
  ['足', 'あし', 'ayak, bacak', 'n', 'vucut'],
  ['お腹', 'おなか', 'karın', 'n', 'vucut', 'お腹が空きました。', 'おなかがすきました。', 'Karnım acıktı.'],
  ['のど', 'のど', 'boğaz', 'n', 'vucut'],
  ['熱', 'ねつ', 'ateş (hastalık)', 'n', 'vucut', '熱があります。', 'ねつがあります。', 'Ateşim var.'],
  ['風邪', 'かぜ', 'nezle, soğuk algınlığı', 'n', 'vucut', '風邪をひきました。', 'かぜをひきました。', 'Nezle oldum.'],
  ['薬', 'くすり', 'ilaç', 'n', 'vucut', '薬を飲みます。', 'くすりをのみます。', 'İlaç içiyorum.'],
  ['病気', 'びょうき', 'hastalık', 'n', 'vucut'],
  ['痛い', 'いたい', 'ağrıyan, acıyan', 'adji', 'sifat'],

  // ————— Günlük hayat ve fiiller (Genki 8–12 civarı) —————
  ['掃除', 'そうじ', 'temizlik', 'n', 'nesne'],
  ['洗濯', 'せんたく', 'çamaşır yıkama', 'n', 'nesne'],
  ['料理', 'りょうり', 'yemek (pişirme)', 'n', 'yemek', '料理を作るのが好きです。', 'りょうりをつくるのがすきです。', 'Yemek yapmayı severim.'],
  ['買い物', 'かいもの', 'alışveriş', 'n', 'nesne'],
  ['旅行', 'りょこう', 'seyahat', 'n', 'nesne'],
  ['試験', 'しけん', 'sınav', 'n', 'nesne', '明日試験があります。', 'あしたしけんがあります。', 'Yarın sınavım var.'],
  ['宿題', 'しゅくだい', 'ödev', 'n', 'nesne'],
  ['仕事', 'しごと', 'iş', 'n', 'nesne'],
  ['映画', 'えいが', 'film', 'n', 'nesne'],
  ['音楽', 'おんがく', 'müzik', 'n', 'nesne'],
  ['天気', 'てんき', 'hava durumu', 'n', 'zaman', 'いい天気ですね。', 'いいてんきですね。', 'Hava güzel, değil mi?'],
  ['雨', 'あめ', 'yağmur', 'n', 'zaman', '明日は雨でしょう。', 'あしたはあめでしょう。', 'Yarın yağmurlu olur herhâlde.'],
  ['雪', 'ゆき', 'kar', 'n', 'zaman'],
  ['泳ぐ', 'およぐ', 'yüzmek', 'v5', 'fiil'],
  ['走る', 'はしる', 'koşmak', 'v5', 'fiil'],
  ['考える', 'かんがえる', 'düşünmek', 'v1', 'fiil'],
  ['思う', 'おもう', 'sanmak, düşünmek', 'v5', 'fiil', '明日は雨が降ると思います。', 'あしたはあめがふるとおもいます。', 'Yarın yağmur yağar sanırım.'],
  ['言う', 'いう', 'söylemek', 'v5', 'fiil'],
  ['降る', 'ふる', 'yağmak', 'v5', 'fiil'],
  ['疲れる', 'つかれる', 'yorulmak', 'v1', 'fiil', '疲れているので、休みます。', 'つかれているので、やすみます。', 'Yorgun olduğum için dinleniyorum.'],
  ['忘れる', 'わすれる', 'unutmak', 'v1', 'fiil'],
  ['覚える', 'おぼえる', 'ezberlemek, hatırlamak', 'v1', 'fiil'],
  ['始まる', 'はじまる', 'başlamak', 'v5', 'fiil'],
  ['終わる', 'おわる', 'bitmek', 'v5', 'fiil'],
  ['なる', 'なる', 'olmak, dönüşmek', 'v5', 'fiil', '寒くなりました。', 'さむくなりました。', 'Hava soğudu.'],
  ['たぶん', 'たぶん', 'muhtemelen', 'adv', 'zarf'],
  ['いつも', 'いつも', 'her zaman', 'adv', 'zarf'],
  ['大変', 'たいへん', 'zor, yorucu', 'adjna', 'sifat'],
  ['楽', 'らく', 'rahat, kolay', 'adjna', 'sifat'],
]

function slug(term: string, reading: string): string {
  return `ja-${reading || term}`
}

export const VOCAB_JA: Vocab[] = ROWS.map(([term, reading, tr, pos, tag, ex, exR, exTr]) => ({
  id: slug(term, reading),
  lang: 'ja' as const,
  term,
  reading,
  tr,
  pos: POS_TR[pos] ?? pos,
  level: 'N5' as const,
  tags: [tag, pos],
  examples: ex ? [{ text: ex, reading: exR, tr: exTr ?? '' }] : [],
  kanji: [...term].filter((c) => /[一-龯]/.test(c)),
}))

export const VOCAB_JA_BY_ID = new Map(VOCAB_JA.map((v) => [v.id, v]))

export const VOCAB_JA_THEMES: { id: string; title: string }[] = [
  { id: 'selamlasma', title: 'Selamlaşma ve kalıplar' },
  { id: 'zamir', title: 'Zamirler ve işaretler' },
  { id: 'soru', title: 'Soru sözcükleri' },
  { id: 'insan', title: 'İnsanlar ve aile' },
  { id: 'yer', title: 'Yerler' },
  { id: 'nesne', title: 'Nesneler' },
  { id: 'yemek', title: 'Yiyecek ve içecek' },
  { id: 'zaman', title: 'Zaman' },
  { id: 'fiil', title: 'Fiiller' },
  { id: 'sifat', title: 'Sıfatlar' },
  { id: 'zarf', title: 'Zarflar' },
  { id: 'vucut', title: 'Vücut ve sağlık' },
  { id: 'baglac', title: 'Bağlaçlar' },
]

export function vocabByTheme(theme: string): Vocab[] {
  return VOCAB_JA.filter((v) => v.tags?.includes(theme))
}
